# permissions for end users to view arithemetics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: arithemetic-viewer-role
rules:
- apiGroups:
  - maths.stream.com
  resources:
  - arithemetics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - maths.stream.com
  resources:
  - arithemetics/status
  verbs:
  - get
