
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - maths.stream.com
  resources:
  - arithemetics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - maths.stream.com
  resources:
  - arithemetics/status
  verbs:
  - get
  - patch
  - update
